"""
Shared helpers for MUTE's Blender model scripts.

Every model in the game is generated by a Python script in this folder (models-as-code), so it can
be rebuilt, tweaked and reviewed like any other source file. Scripts run headless through the
`bpy` package (Blender 5.0.1 as a Python module): see art/README.md.

Conventions (the renderer relies on them):
  * Units are meters. Blender is Z-up; the glTF exporter converts to three.js Y-up.
  * The FRONT of every model faces Blender +Y, which becomes three.js -Z (= yaw 0 in the game).
  * Origin: floor contact point (bottom center) for furniture/props/characters, unless the
    asset's README entry says otherwise (e.g. hands: the wrist).
  * glTF only exports IMAGE textures, so procedural materials must be baked (see `bake`).
"""

from __future__ import annotations

import math
import os
from typing import Iterable, Sequence

import bpy
import bmesh
from mathutils import Vector

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
MODELS_DIR = os.path.join(REPO, 'public', 'models')
PREVIEW_DIR = os.path.join(REPO, 'art', 'previews')


# ---------------------------------------------------------------------------------------------
# Scene
# ---------------------------------------------------------------------------------------------

def reset() -> bpy.types.Scene:
    """Empty scene, metric units, Cycles on CPU (the only engine that works headless here)."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = 'METRIC'
    scene.render.engine = 'CYCLES'
    scene.cycles.device = 'CPU'
    scene.cycles.samples = 32
    return scene


def activate(obj: bpy.types.Object, select: Sequence[bpy.types.Object] | None = None) -> None:
    for o in bpy.context.view_layer.objects:
        o.select_set(False)
    for o in (select or [obj]):
        o.select_set(True)
    bpy.context.view_layer.objects.active = obj


def apply_modifiers(obj: bpy.types.Object) -> None:
    """Bake the modifier stack into the mesh (robust headless; no operator context needed)."""
    deps = bpy.context.evaluated_depsgraph_get()
    mesh = bpy.data.meshes.new_from_object(obj.evaluated_get(deps))
    old = obj.data
    obj.modifiers.clear()
    obj.data = mesh
    if old.users == 0:
        bpy.data.meshes.remove(old)


def apply_transform(obj: bpy.types.Object, location=False, rotation=True, scale=True) -> None:
    activate(obj)
    bpy.ops.object.transform_apply(location=location, rotation=rotation, scale=scale)


def join(objects: Sequence[bpy.types.Object], name: str | None = None) -> bpy.types.Object:
    """Join meshes into the first one (materials are kept per face)."""
    objects = [o for o in objects if o.type == 'MESH']
    target = objects[0]
    with bpy.context.temp_override(
        active_object=target, selected_editable_objects=objects, selected_objects=objects
    ):
        bpy.ops.object.join()
    if name:
        target.name = name
        target.data.name = name
    return target


def smooth(obj: bpy.types.Object, angle_deg: float = 40.0) -> None:
    """Smooth shading with sharp edges kept above `angle_deg`."""
    activate(obj)
    try:
        bpy.ops.object.shade_smooth_by_angle(angle=math.radians(angle_deg))
    except Exception:  # older API fallback
        bpy.ops.object.shade_smooth()


def tri_count(objects: Iterable[bpy.types.Object]) -> int:
    deps = bpy.context.evaluated_depsgraph_get()
    total = 0
    for o in objects:
        if o.type != 'MESH':
            continue
        m = o.evaluated_get(deps).to_mesh()
        m.calc_loop_triangles()
        total += len(m.loop_triangles)
        o.evaluated_get(deps).to_mesh_clear()
    return total


def decimate_to(obj: bpy.types.Object, max_tris: int) -> None:
    """Collapse-decimate a mesh down to roughly `max_tris` triangles (no-op if already under)."""
    current = tri_count([obj])
    if current <= max_tris:
        return
    mod = obj.modifiers.new('decimate', 'DECIMATE')
    mod.ratio = max_tris / current
    mod.use_collapse_triangulate = True
    apply_modifiers(obj)


def uv_unwrap(obj: bpy.types.Object, margin: float = 0.01, angle_deg: float = 66.0) -> None:
    activate(obj)
    bpy.ops.object.mode_set(mode='EDIT')
    bpy.ops.mesh.select_all(action='SELECT')
    bpy.ops.uv.smart_project(angle_limit=math.radians(angle_deg), island_margin=margin)
    bpy.ops.object.mode_set(mode='OBJECT')


def set_origin_bottom_center(obj: bpy.types.Object) -> None:
    """Move the object's origin to the center of its bounding box bottom, then put it at 0,0,0."""
    pts = [obj.matrix_world @ Vector(c) for c in obj.bound_box]
    lo = Vector((min(p.x for p in pts), min(p.y for p in pts), min(p.z for p in pts)))
    hi = Vector((max(p.x for p in pts), max(p.y for p in pts), max(p.z for p in pts)))
    pivot = Vector(((lo.x + hi.x) / 2, (lo.y + hi.y) / 2, lo.z))
    obj.data.transform(__import__('mathutils').Matrix.Translation(-(pivot - obj.location)))
    obj.location = (0, 0, 0)


# ---------------------------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------------------------

def _bsdf(mat: bpy.types.Material) -> bpy.types.Node:
    nt = mat.node_tree
    for n in nt.nodes:
        if n.type == 'BSDF_PRINCIPLED':
            return n
    out = next((n for n in nt.nodes if n.type == 'OUTPUT_MATERIAL'), None) or nt.nodes.new('ShaderNodeOutputMaterial')
    b = nt.nodes.new('ShaderNodeBsdfPrincipled')
    nt.links.new(b.outputs['BSDF'], out.inputs['Surface'])
    return b


def material(
    name: str,
    color=(0.5, 0.5, 0.5),
    roughness: float = 0.6,
    metallic: float = 0.0,
    emission=None,
    emission_strength: float = 1.0,
    alpha: float = 1.0,
) -> bpy.types.Material:
    """Plain Principled BSDF material (exports to glTF as-is, no baking needed)."""
    mat = bpy.data.materials.new(name)
    try:
        mat.use_nodes = True  # deprecated (always on) in newer Blender
    except Exception:
        pass
    b = _bsdf(mat)
    b.inputs['Base Color'].default_value = (*color, 1.0)
    b.inputs['Roughness'].default_value = roughness
    b.inputs['Metallic'].default_value = metallic
    if emission is not None:
        b.inputs['Emission Color'].default_value = (*emission, 1.0)
        b.inputs['Emission Strength'].default_value = emission_strength
    if alpha < 1.0:
        b.inputs['Alpha'].default_value = alpha
        for attr, value in (('surface_render_method', 'BLENDED'), ('blend_method', 'BLEND')):
            try:
                setattr(mat, attr, value)
            except Exception:
                pass
    return mat


def assign(obj: bpy.types.Object, mat: bpy.types.Material) -> None:
    obj.data.materials.clear()
    obj.data.materials.append(mat)


# ---------------------------------------------------------------------------------------------
# Baking (procedural / high-poly detail -> image textures that glTF can carry)
# ---------------------------------------------------------------------------------------------

def _zero_metallic(obj: bpy.types.Object):
    """Set every Principled 'Metallic' on obj's materials to 0 (unlinking textures); returns undo."""
    saved = []
    for mat in obj.data.materials:
        if not mat or not mat.node_tree:
            continue
        nt = mat.node_tree
        for n in nt.nodes:
            if n.type != 'BSDF_PRINCIPLED':
                continue
            sock = n.inputs['Metallic']
            links = [(l.from_socket, l.to_socket) for l in sock.links]
            for l in list(sock.links):
                nt.links.remove(l)
            saved.append((nt, sock, sock.default_value, links))
            sock.default_value = 0.0

    def undo() -> None:
        for nt, sock, value, links in saved:
            sock.default_value = value
            for a, b in links:
                nt.links.new(a, b)

    return undo


def bake(
    low: bpy.types.Object,
    name: str,
    size: int = 1024,
    high: bpy.types.Object | None = None,
    normal: bool = True,
    roughness: bool = True,
    emission: bool = False,
    cage_extrusion: float = 0.03,
    margin: int = 8,
    samples: int = 4,
) -> bpy.types.Material:
    """
    Bake base color (+ roughness, + tangent-space normal, + emission) into images and replace
    `low`'s materials with a single image-textured material named `name`.

    Without `high`, bakes `low`'s own (procedural) materials. With `high`, bakes the high-poly
    object's surface (color + detail normals) onto `low` (selected-to-active). `low` needs UVs
    (call uv_unwrap first) and `high` should overlap `low` closely.
    """
    scene = bpy.context.scene
    scene.render.engine = 'CYCLES'
    scene.cycles.samples = samples

    def new_image(suffix: str, non_color: bool) -> bpy.types.Image:
        img = bpy.data.images.new(f'{name}_{suffix}', size, size, alpha=False, float_buffer=False)
        if non_color:
            img.colorspace_settings.name = 'Non-Color'
        return img

    # Every material on the object being baked INTO needs an active image node pointing at the
    # target image. With selected-to-active that's the low-poly; otherwise also the low-poly.
    if not low.data.materials:
        assign(low, material(f'{name}_tmp'))

    def target(img: bpy.types.Image) -> None:
        for mat in low.data.materials:
            nt = mat.node_tree
            node = nt.nodes.get('__bake_target__') or nt.nodes.new('ShaderNodeTexImage')
            node.name = '__bake_target__'
            node.image = img
            for n in nt.nodes:
                n.select = False
            node.select = True
            nt.nodes.active = node

    sel = [high, low] if high else [low]
    common = dict(margin=margin, use_selected_to_active=bool(high), cage_extrusion=cage_extrusion if high else 0.0)

    passes: list[tuple[str, bpy.types.Image]] = []

    color = new_image('color', False)
    target(color)
    activate(low, sel)
    # Cycles' diffuse-color pass is black on metallic surfaces, so bake color with metalness
    # temporarily at 0 (and unlinked), then restore it.
    source = high if high else low
    restore = _zero_metallic(source)
    try:
        bpy.ops.object.bake(type='DIFFUSE', pass_filter={'COLOR'}, **common)
    finally:
        restore()
    passes.append(('color', color))

    if roughness:
        rough = new_image('rough', True)
        target(rough)
        activate(low, sel)
        bpy.ops.object.bake(type='ROUGHNESS', **common)
        passes.append(('rough', rough))

    if normal:
        nrm = new_image('normal', True)
        target(nrm)
        activate(low, sel)
        bpy.ops.object.bake(type='NORMAL', normal_space='TANGENT', **common)
        passes.append(('normal', nrm))

    if emission:
        emi = new_image('emit', False)
        target(emi)
        activate(low, sel)
        bpy.ops.object.bake(type='EMIT', **common)
        passes.append(('emit', emi))

    for _, img in passes:
        img.pack()

    # Replace with one clean, exporter-friendly material.
    mat = bpy.data.materials.new(name)
    try:
        mat.use_nodes = True
    except Exception:
        pass
    nt = mat.node_tree
    b = _bsdf(mat)
    imgs = dict(passes)

    def tex(img: bpy.types.Image, x: float, y: float) -> bpy.types.Node:
        n = nt.nodes.new('ShaderNodeTexImage')
        n.image = img
        n.location = (x, y)
        return n

    nt.links.new(tex(imgs['color'], -600, 300).outputs['Color'], b.inputs['Base Color'])
    if 'rough' in imgs:
        nt.links.new(tex(imgs['rough'], -600, 0).outputs['Color'], b.inputs['Roughness'])
    if 'normal' in imgs:
        nm = nt.nodes.new('ShaderNodeNormalMap')
        nm.location = (-250, -300)
        nt.links.new(tex(imgs['normal'], -600, -300).outputs['Color'], nm.inputs['Color'])
        nt.links.new(nm.outputs['Normal'], b.inputs['Normal'])
    if 'emit' in imgs:
        nt.links.new(tex(imgs['emit'], -600, -600).outputs['Color'], b.inputs['Emission Color'])
        b.inputs['Emission Strength'].default_value = 1.0
    assign(low, mat)
    return mat


# ---------------------------------------------------------------------------------------------
# Export + previews
# ---------------------------------------------------------------------------------------------

def export_glb(
    name: str,
    objects: Sequence[bpy.types.Object] | None = None,
    animations: bool = False,
    image_format: str = 'WEBP',
) -> str:
    """Export to public/models/<name>.glb. `objects` = what to export (plus their children)."""
    os.makedirs(MODELS_DIR, exist_ok=True)
    path = os.path.join(MODELS_DIR, f'{name}.glb')
    if objects:
        everything: list[bpy.types.Object] = []
        for o in objects:
            everything.append(o)
            everything.extend(o.children_recursive)
        activate(everything[0], everything)
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format='GLB',
        use_selection=bool(objects),
        export_apply=True,
        export_yup=True,
        export_texcoords=True,
        export_tangents=True,
        export_normals=True,
        export_materials='EXPORT',
        export_image_format=image_format,
        export_animations=animations,
        export_animation_mode='ACTIONS',
        export_skins=True,
        export_lights=False,
        export_cameras=False,
        export_extras=True,
    )
    print(f'[export] {path}  ({os.path.getsize(path) / 1024:.0f} KB)')
    return path


def _bounds(objects: Sequence[bpy.types.Object]) -> tuple[Vector, Vector]:
    deps = bpy.context.evaluated_depsgraph_get()
    lo = Vector((1e9, 1e9, 1e9))
    hi = Vector((-1e9, -1e9, -1e9))
    for o in objects:
        if o.type != 'MESH':
            continue
        ev = o.evaluated_get(deps)
        for c in ev.bound_box:
            p = ev.matrix_world @ Vector(c)
            lo = Vector((min(lo.x, p.x), min(lo.y, p.y), min(lo.z, p.z)))
            hi = Vector((max(hi.x, p.x), max(hi.y, p.y), max(hi.z, p.z)))
    return lo, hi


def preview(
    name: str,
    objects: Sequence[bpy.types.Object] | None = None,
    yaw_deg: float = 35.0,
    pitch_deg: float = 15.0,
    size: int = 640,
    mood: str = 'studio',
    samples: int = 48,
    zoom: float = 1.0,
) -> str:
    """
    Render art/previews/<name>.png so the model can be reviewed.
    yaw 0 = looking at the model's FRONT (camera on the +Y side looking toward -Y).
    mood: 'studio' (neutral gray, soft 3-point light) or 'flash' (black room, one hard
    camera-flash light from the viewer, like in game).
    """
    os.makedirs(PREVIEW_DIR, exist_ok=True)
    scene = bpy.context.scene
    objects = list(objects or [o for o in scene.objects if o.type == 'MESH'])
    lo, hi = _bounds(objects)
    center = (lo + hi) / 2
    radius = max((hi - lo).length / 2, 0.05)

    temp: list[bpy.types.Object] = []
    cam_data = bpy.data.cameras.new('__prev_cam')
    cam_data.lens = 50
    cam = bpy.data.objects.new('__prev_cam', cam_data)
    scene.collection.objects.link(cam)
    temp.append(cam)
    fov = 2 * math.atan(cam_data.sensor_width / (2 * cam_data.lens))
    dist = radius / math.sin(fov / 2) * 1.08 / zoom
    yaw, pitch = math.radians(yaw_deg), math.radians(pitch_deg)
    direction = Vector((math.sin(yaw) * math.cos(pitch), math.cos(yaw) * math.cos(pitch), math.sin(pitch)))
    cam.location = center + direction * dist
    cam.rotation_euler = (center - cam.location).to_track_quat('-Z', 'Y').to_euler()
    scene.camera = cam

    def light(kind: str, energy: float, loc: Vector, size_: float = 1.0, color=(1, 1, 1)):
        data = bpy.data.lights.new(f'__prev_{kind}_{len(temp)}', kind)
        data.energy = energy
        data.color = color
        if kind == 'AREA':
            data.size = size_
        if kind == 'SPOT':
            data.spot_size = math.radians(70)
            data.shadow_soft_size = 0.02
        o = bpy.data.objects.new(data.name, data)
        o.location = loc
        o.rotation_euler = (center - loc).to_track_quat('-Z', 'Y').to_euler()
        scene.collection.objects.link(o)
        temp.append(o)

    world = scene.world or bpy.data.worlds.new('World')
    scene.world = world
    try:
        world.use_nodes = True
    except Exception:
        pass
    bg = next((n for n in world.node_tree.nodes if n.type == 'BACKGROUND'), None)
    r = radius * 4
    if mood == 'flash':
        if bg:
            bg.inputs['Color'].default_value = (0.0, 0.0, 0.0, 1)
            bg.inputs['Strength'].default_value = 0.0
        light('SPOT', 18 * r * r, cam.location + Vector((0, 0, 0.05)))
        light('POINT', 2 * r * r, center + Vector((-r, -r, r)), color=(0.55, 0.65, 1.0))
    else:
        if bg:
            bg.inputs['Color'].default_value = (0.18, 0.18, 0.19, 1)
            bg.inputs['Strength'].default_value = 0.6
        light('AREA', 60 * r * r, center + Vector((r, r * 0.6, r * 1.2)), size_=r)
        light('AREA', 20 * r * r, center + Vector((-r * 1.2, r * 0.4, r * 0.4)), size_=r)
        light('AREA', 40 * r * r, center + Vector((0, -r * 1.3, r)), size_=r)

    scene.cycles.samples = samples
    scene.render.resolution_x = size
    scene.render.resolution_y = size
    scene.render.film_transparent = False
    path = os.path.join(PREVIEW_DIR, f'{name}.png')
    scene.render.filepath = path
    bpy.ops.render.render(write_still=True)

    for o in temp:
        data = o.data
        bpy.data.objects.remove(o)
        if isinstance(data, bpy.types.Camera):
            bpy.data.cameras.remove(data)
        elif isinstance(data, bpy.types.Light):
            bpy.data.lights.remove(data)
    print(f'[preview] {path}')
    return path


def report(name: str, objects: Sequence[bpy.types.Object]) -> None:
    print(f'[report] {name}: {tri_count(objects)} triangles, {len(objects)} objects')
