"""
Regenerate art/GALLERY.md: every preview render in art/previews, grouped by asset, so the models
can be browsed on GitHub. Run: python3 art/gallery.py   (no Blender needed)
"""

import os
import re
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
PREVIEWS = os.path.join(HERE, 'previews')
MODELS = os.path.join(HERE, '..', 'public', 'models')

GROUPS = OrderedDict(
    [
        ('The monster', r'^monster'),
        ('Hands', r'^hand'),
        ('Players', r'^avatar'),
        ('Camera, fuses, film', r'^(camera|fuse_|fuse\.|fuse$|film)'),
        ('Fuse box and front door', r'^(fusebox|door)'),
        ('Furniture', r'^furniture'),
        ('Set dressing', r'^dressing'),
    ]
)

# Show the most telling shots first within a group.
ORDER = ['lineup', 'threejs', 'flash', '3q', 'front', 'side', 'walk', 'attack']


def rank(name: str) -> tuple:
    for i, key in enumerate(ORDER):
        if key in name:
            return (i, name)
    return (len(ORDER), name)


def main() -> None:
    files = sorted(f for f in os.listdir(PREVIEWS) if f.endswith('.png') and not f.startswith('_'))
    used = set()
    lines = [
        '# MUTE model gallery',
        '',
        'Every model is generated by a Blender script in `art/blender/` (see `art/README.md`).',
        'Renders below are Blender previews (`*_3q`, `*_flash` = in-game camera-flash lighting) and',
        'screenshots from the actual three.js game renderer (`*_threejs`).',
        '',
    ]
    models = sorted(f[:-4] for f in os.listdir(MODELS) if f.endswith('.glb')) if os.path.isdir(MODELS) else []
    if models:
        lines += [f'**{len(models)} models in the game:** ' + ', '.join(f'`{m}`' for m in models), '']
    for title, pattern in GROUPS.items():
        group = sorted((f for f in files if re.search(pattern, f) and f not in used), key=rank)
        if not group:
            continue
        used.update(group)
        lines += [f'## {title}', '']
        for f in group:
            label = f[:-4].replace('_', ' ')
            lines += [f'**{label}**', '', f'![{label}](previews/{f})', '']
    rest = [f for f in files if f not in used]
    if rest:
        lines += ['## Other', '']
        for f in rest:
            lines += [f'![{f[:-4]}](previews/{f})', '']
    with open(os.path.join(HERE, 'GALLERY.md'), 'w') as fh:
        fh.write('\n'.join(lines))
    print(f'wrote art/GALLERY.md ({len(files)} images)')


if __name__ == '__main__':
    main()
