#!/usr/bin/env node
/**
 * Build-time GPU texture compression for the Blender assets (KTX2 / Basis Universal).
 *
 * The sources in public/ stay exactly as the Blender pipeline exports them (WebP inside the GLBs,
 * WebP surface sets). This writes GPU-compressed COPIES next to them in the build output:
 *
 *   <out>/models/ktx2/<name>.glb      every public/models/<name>.glb, textures re-encoded as KTX2
 *   <out>/models/ktx2/manifest.json   names of the converted models
 *   <out>/textures/<set>_<map>.ktx2   every surface set listed in public/textures/textures.json
 *   <out>/textures/textures.json      that index, with "ktx2": true on the converted sets
 *
 * The game (ModelLibrary / SurfaceLibrary) loads these when they exist and its KTX2 transcoder
 * works, else the WebP originals, which Vite copies to <out>/ untouched. Without this step (plain
 * `npm run dev`) everything simply uses WebP.
 *
 * Why: WebP is small to download but the GPU stores it as raw RGBA8 (4 B/px + mips). Basis
 * transcodes on the device to a format the GPU samples directly: on Quest ETC2 (0.5 B/px, 1 with
 * alpha) for ETC1S and ASTC 4x4 (1 B/px) for UASTC, so texture memory drops ~4-8x.
 *
 * Encodings (see ENCODINGS): color = ETC1S sRGB; ORM / roughness-metal / occlusion = ETC1S linear;
 * normal maps = ETC1S normal-map mode, except the close-up hero assets and the house surfaces
 * (UASTC_NORMALS), which get UASTC + RDO + Zstandard. Mipmaps are generated by the encoder.
 * Textures larger than their on-screen need are downscaled first (MAX_SIZE).
 *
 * Usage:
 *   node scripts/optimize-assets.mjs [outDir=dist] [--src public] [--only monster,fuse] [--no-cache]
 * Also used by vite.config.ts when the dev server runs with MUTE_KTX2=1.
 *
 * Encoded textures are cached by content hash (node_modules/.cache/mute-ktx2), so only changed
 * textures are re-encoded. The encoder is a WASM build of Basis Universal (npm ktx2-encoder),
 * run in a pool of worker threads; images are decoded/resized with sharp.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { availableParallelism } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { isMainThread, parentPort, Worker, workerData } from 'node:worker_threads';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
/** Bump to invalidate the cache when the encoder or the settings below change meaningfully. */
const CACHE_TAG = 'mute-ktx2-v1';

// ---------------------------------------------------------------------------------------------
// Policy
// ---------------------------------------------------------------------------------------------

/** Basis encoder settings per texture kind (ktx2-encoder options). */
const ENCODINGS = {
  /** baseColor / emissive: perceptual sRGB. */
  color: { isUASTC: false, qualityLevel: 160, compressionLevel: 2, isPerceptual: true, isSetKTX2SRGBTransferFunc: true },
  /** ORM / metallicRoughness / occlusion: linear data. */
  data: { isUASTC: false, qualityLevel: 200, compressionLevel: 2, isPerceptual: false, isSetKTX2SRGBTransferFunc: false },
  /** Normal maps (most props): ETC1S tuned for normals. Tiny download, 0.5 B/px on the GPU. */
  normal: { isUASTC: false, qualityLevel: 230, compressionLevel: 2, isNormalMap: true, isPerceptual: false, isSetKTX2SRGBTransferFunc: false },
  /** Normal maps that are seen up close / everywhere: UASTC (-> ASTC 4x4) + RDO + Zstandard. */
  normalHQ: {
    isUASTC: true, uastcLDRQualityLevel: 1, enableRDO: true, rdoQualityLevel: 1, needSupercompression: true,
    isNormalMap: true, isPerceptual: false, isSetKTX2SRGBTransferFunc: false,
  },
};

/** Models (by name) and surface sets whose normal maps get UASTC: hero assets and the walls/floors. */
const UASTC_NORMALS = /^(monster|hand_left|hand_right|surface:.*)$/;

/**
 * Max texture size (px, longest side) by asset name + texture kind. Everything else keeps its
 * size (art/README.md budgets already target Quest: props 512, furniture 1024, monster 2048).
 * Batched models (furniture_*, dressing_*, trims) must keep consistent sizes within a family:
 * the renderer merges same-size textures of different models into texture arrays.
 */
const MAX_SIZE = [
  // The monster's roughness/AO doesn't need 2048 (its color + normal keep it).
  { name: /^monster$/, kind: /^data$/, max: 1024 },
  // Small hand-held / floor props.
  { name: /^fuse$/, kind: /.*/, max: 512 },
];

// ---------------------------------------------------------------------------------------------
// Encoder worker
// ---------------------------------------------------------------------------------------------

if (!isMainThread && workerData?.mute === 'ktx2-encoder') {
  // The WASM encoder prints progress to stdout; keep the build log readable.
  console.log = console.info = console.debug = console.warn = () => {};
  const { encodeToKTX2 } = await import('ktx2-encoder');
  parentPort.on('message', async ({ id, data, width, height, options }) => {
    try {
      const out = await encodeToKTX2(data, { ...options, generateMipmap: true, imageDecoder: async () => ({ data, width, height }) });
      parentPort.postMessage({ id, out }, [out.buffer]);
    } catch (e) {
      parentPort.postMessage({ id, error: String(e?.stack ?? e) });
    }
  });
}

class EncoderPool {
  constructor(size) {
    this.size = size;
    this.workers = [];
    this.idle = [];
    this.queue = [];
    this.pending = new Map();
    this.nextId = 1;
  }

  spawn() {
    const w = new Worker(fileURLToPath(import.meta.url), { workerData: { mute: 'ktx2-encoder' }, stdout: true, stderr: true });
    w.stdout.resume();
    w.stderr.resume();
    w.on('message', ({ id, out, error }) => {
      const job = this.pending.get(id);
      this.pending.delete(id);
      if (error) job.reject(new Error(error));
      else job.resolve(new Uint8Array(out.buffer ?? out));
      this.idle.push(w);
      this.pump();
    });
    w.on('error', (e) => {
      for (const job of this.pending.values()) job.reject(e);
      this.pending.clear();
    });
    this.workers.push(w);
    this.idle.push(w);
  }

  encode(data, width, height, options) {
    return new Promise((resolve, reject) => {
      this.queue.push({ data, width, height, options, resolve, reject });
      if (!this.idle.length && this.workers.length < this.size) this.spawn();
      this.pump();
    });
  }

  pump() {
    while (this.idle.length && this.queue.length) {
      const w = this.idle.pop();
      const job = this.queue.shift();
      const id = this.nextId++;
      this.pending.set(id, job);
      w.postMessage({ id, data: job.data, width: job.width, height: job.height, options: job.options }, [job.data.buffer]);
    }
  }

  async close() {
    await Promise.all(this.workers.map((w) => w.terminate()));
  }
}

// ---------------------------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------------------------

/** GPU bytes per pixel on Quest: ETC1S -> ETC1/ETC2 RGB (0.5) or ETC2 RGBA (1); UASTC -> ASTC 4x4 (1). */
function questBpp(options, hasAlpha) {
  if (options.isUASTC) return 1;
  return hasAlpha ? 1 : 0.5;
}
const MIPS = 4 / 3;

function maxSizeFor(name, kind) {
  let max = Infinity;
  for (const r of MAX_SIZE) if (r.name.test(name) && r.kind.test(kind)) max = Math.min(max, r.max);
  return max;
}

/** Texture kind from the glTF material slots that use it. */
function kindOfSlots(slots) {
  if (slots.includes('normalTexture')) return 'normal';
  if (slots.includes('baseColorTexture') || slots.includes('emissiveTexture')) return 'color';
  return 'data';
}

const fmtMB = (b) => `${(b / 1048576).toFixed(1)} MB`;

class Optimizer {
  constructor({ cacheDir, useCache, log }) {
    this.cacheDir = cacheDir;
    this.useCache = useCache;
    this.log = log;
    this.pool = new EncoderPool(Math.max(1, Math.min(4, availableParallelism())));
    this.inflight = new Map();
    this.stats = { textures: 0, encoded: 0, cached: 0, gpuBefore: 0, gpuAfter: 0, byKind: {} };
    mkdirSync(cacheDir, { recursive: true });
  }

  /**
   * Decode (and maybe downscale/flip) an image, then encode it to KTX2 with the options of its
   * kind. Returns { ktx2, key, width, height }.
   */
  async encodeImage(sharp, bytes, { kind, label, maxSize = Infinity, flipY = false, hq = false }) {
    let img = sharp(bytes, { limitInputPixels: false });
    const meta = await img.metadata();
    let { width, height } = meta;
    const longest = Math.max(width, height);
    if (longest > maxSize) {
      const k = maxSize / longest;
      width = Math.max(4, Math.round(width * k));
      height = Math.max(4, Math.round(height * k));
      img = img.resize(width, height, { kernel: 'lanczos3', fit: 'fill' });
    }
    const raw = await img.ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    width = raw.info.width;
    height = raw.info.height;
    const data = new Uint8Array(raw.data.buffer, raw.data.byteOffset, raw.data.byteLength);
    let hasAlpha = false;
    for (let i = 3; i < data.length; i += 4) if (data[i] !== 255) { hasAlpha = true; break; }
    const encKind = kind === 'normal' && hq ? 'normalHQ' : kind;
    const options = { ...ENCODINGS[encKind], isYFlip: flipY };
    const key = createHash('sha1')
      .update(CACHE_TAG).update(JSON.stringify(options)).update(`${width}x${height}`).update(data)
      .digest('hex');

    const s = this.stats;
    s.textures++;
    s.gpuBefore += meta.width * meta.height * 4 * MIPS;
    const after = width * height * questBpp(options, hasAlpha) * MIPS;
    s.gpuAfter += after;
    const k = (s.byKind[encKind] ??= { count: 0, gpu: 0, bytes: 0 });
    k.count++;
    k.gpu += after;

    const cached = join(this.cacheDir, `${key}.ktx2`);
    let ktx2;
    if (this.useCache && existsSync(cached)) {
      ktx2 = new Uint8Array(readFileSync(cached));
      s.cached++;
    } else {
      let job = this.inflight.get(key);
      if (!job) {
        const t0 = Date.now();
        job = this.pool.encode(new Uint8Array(data), width, height, options).then((out) => {
          writeFileSync(cached, out);
          s.encoded++;
          this.log(`  encoded ${label} ${width}x${height} ${encKind}${hasAlpha ? '+alpha' : ''} -> ${(out.byteLength / 1024).toFixed(0)} KB (${((Date.now() - t0) / 1000).toFixed(1)} s)`);
          return out;
        });
        this.inflight.set(key, job);
      }
      ktx2 = await job;
    }
    k.bytes += ktx2.byteLength;
    return { ktx2, key, width, height };
  }

  close() {
    return this.pool.close();
  }
}

// ---------------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------------

/**
 * Write KTX2 copies of every model + surface set from `srcDir` (public/) into `outDir`.
 * Returns a summary (also logged).
 */
export async function optimizeAssets({
  srcDir = join(ROOT, 'public'),
  outDir = join(ROOT, 'dist'),
  cacheDir = join(ROOT, 'node_modules', '.cache', 'mute-ktx2'),
  only = null,
  useCache = true,
  log = (msg) => console.log(msg),
} = {}) {
  const t0 = Date.now();
  const [{ NodeIO }, ext, { default: sharp }] = await Promise.all([
    import('@gltf-transform/core'),
    import('@gltf-transform/extensions'),
    import('sharp'),
  ]);
  const io = new NodeIO().registerExtensions(ext.ALL_EXTENSIONS);
  const opt = new Optimizer({ cacheDir, useCache, log });
  const summary = { models: [], surfaces: [], downloadBefore: 0, downloadAfter: 0 };

  try {
    // ---- Models ---------------------------------------------------------------------------
    const modelsDir = join(srcDir, 'models');
    const outModels = join(outDir, 'models', 'ktx2');
    mkdirSync(outModels, { recursive: true });
    const names = existsSync(modelsDir)
      ? readdirSync(modelsDir).filter((f) => f.endsWith('.glb') && !f.startsWith('_')).map((f) => f.slice(0, -4)).sort()
      : [];
    const converted = [];
    await Promise.all(names.filter((n) => !only || only.includes(n)).map(async (name) => {
      const src = join(modelsDir, `${name}.glb`);
      try {
        const doc = await io.read(src);
        const root = doc.getRoot();
        const graph = doc.getGraph();
        await Promise.all(root.listTextures().map(async (tex, i) => {
          const mime = tex.getMimeType();
          if (!['image/webp', 'image/png', 'image/jpeg'].includes(mime)) return;
          const slots = [...new Set(graph.listParentEdges(tex).filter((e) => e.getParent() !== root).map((e) => e.getName()))];
          const kind = kindOfSlots(slots);
          const label = `${name}:${tex.getName() || i}`;
          const { ktx2, key } = await opt.encodeImage(sharp, tex.getImage(), {
            kind, label, maxSize: maxSizeFor(name, kind), hq: UASTC_NORMALS.test(name),
          });
          tex.setImage(ktx2).setMimeType('image/ktx2');
          // Content hash in the name: identical textures in different GLBs (both hands, the
          // shared painted-wood trim set, flat glass normals) are shared at runtime.
          tex.setName(`${(tex.getName() || `tex${i}`).replace(/#[0-9a-f]{12}$/, '')}#${key.slice(0, 12)}`);
        }));
        if (root.listTextures().some((t) => t.getMimeType() === 'image/ktx2')) {
          doc.createExtension(ext.KHRTextureBasisu).setRequired(true);
        }
        if (!root.listTextures().some((t) => t.getMimeType() === 'image/webp')) {
          for (const e of root.listExtensionsUsed()) if (e.extensionName === 'EXT_texture_webp') e.dispose();
        }
        const bytes = await io.writeBinary(doc);
        writeFileSync(join(outModels, `${name}.glb`), bytes);
        const before = statSync(src).size;
        summary.downloadBefore += before;
        summary.downloadAfter += bytes.byteLength;
        summary.models.push({ name, before, after: bytes.byteLength });
        converted.push(name);
      } catch (e) {
        log(`  ! ${name}.glb not converted (the game will use the WebP original): ${e?.message ?? e}`);
      }
    }));
    // Keep entries from earlier partial runs (--only) that still have their file.
    const listed = new Set(converted);
    for (const n of names) if (!listed.has(n) && existsSync(join(outModels, `${n}.glb`))) listed.add(n);
    writeFileSync(join(outModels, 'manifest.json'), JSON.stringify([...listed].sort()));

    // ---- Surface texture sets -------------------------------------------------------------
    const texDir = join(srcDir, 'textures');
    const indexPath = join(texDir, 'textures.json');
    if (existsSync(indexPath)) {
      const index = JSON.parse(readFileSync(indexPath, 'utf8'));
      const outTex = join(outDir, 'textures');
      mkdirSync(outTex, { recursive: true });
      await Promise.all(Object.entries(index).map(async ([set, info]) => {
        if (only && !only.includes(set) && !only.includes('textures')) return;
        const maps = Array.isArray(info.maps) ? info.maps : ['color', 'normal', 'orm'];
        try {
          await Promise.all(maps.map(async (map) => {
            const src = join(texDir, `${set}_${map}.webp`);
            const kind = map === 'color' ? 'color' : map === 'normal' ? 'normal' : 'data';
            // TextureLoader flips images on upload (flipY), compressed textures can't be: flip here.
            const { ktx2 } = await opt.encodeImage(sharp, readFileSync(src), {
              kind, label: `${set}_${map}`, flipY: true, hq: UASTC_NORMALS.test(`surface:${set}`),
            });
            writeFileSync(join(outTex, `${set}_${map}.ktx2`), ktx2);
            const before = statSync(src).size;
            summary.downloadBefore += before;
            summary.downloadAfter += ktx2.byteLength;
            summary.surfaces.push({ name: `${set}_${map}`, before, after: ktx2.byteLength });
          }));
          info.ktx2 = true;
        } catch (e) {
          log(`  ! surface set ${set} not converted (the game will use WebP): ${e?.message ?? e}`);
          delete info.ktx2;
        }
      }));
      writeFileSync(join(outTex, 'textures.json'), JSON.stringify(index, null, 2));
    }
  } finally {
    await opt.close();
  }

  const s = opt.stats;
  summary.gpuBefore = s.gpuBefore;
  summary.gpuAfter = s.gpuAfter;
  log(
    `[ktx2] ${summary.models.length} models + ${summary.surfaces.length} surface maps, ${s.textures} textures `
    + `(${s.encoded} encoded, ${s.cached} cached) in ${((Date.now() - t0) / 1000).toFixed(1)} s\n`
    + `[ktx2] est. GPU texture memory (all textures, mips, Quest formats): ${fmtMB(s.gpuBefore)} as RGBA8 -> ${fmtMB(s.gpuAfter)}\n`
    + `[ktx2] download: ${fmtMB(summary.downloadBefore)} (WebP) -> ${fmtMB(summary.downloadAfter)} (KTX2)\n`
    + Object.entries(s.byKind).map(([k, v]) => `[ktx2]   ${k.padEnd(9)} ${String(v.count).padStart(3)} textures, GPU ${fmtMB(v.gpu)}, file ${fmtMB(v.bytes)}`).join('\n'),
  );
  return summary;
}

// CLI
if (isMainThread && process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  const args = process.argv.slice(2);
  const flag = (name) => {
    const i = args.indexOf(name);
    if (i < 0) return undefined;
    const v = args[i + 1];
    args.splice(i, 2);
    return v;
  };
  const noCache = args.includes('--no-cache');
  if (noCache) args.splice(args.indexOf('--no-cache'), 1);
  const src = flag('--src');
  const only = flag('--only');
  const outDir = resolve(args[0] ?? join(ROOT, 'dist'));
  if (!existsSync(outDir)) {
    console.error(`[ktx2] output dir ${outDir} does not exist (run vite build first)`);
    process.exit(1);
  }
  optimizeAssets({
    outDir,
    srcDir: src ? resolve(src) : undefined,
    only: only ? only.split(',') : null,
    useCache: !noCache,
  }).catch((e) => {
    console.error('[ktx2] failed:', e);
    process.exit(1);
  });
}
